INSERT INTO medical_history (mh_id,patient_id,surgeries,allergies,medical_conditions) VALUES
(nextval('seq_mh_id'),'00001','Hernia Repair','Shellfish','Bronchitis'),
(nextval('seq_mh_id'),'00002','Appendectomy','Dust','Arthritis'),
(nextval('seq_mh_id'),'00003','Cataract Surgery','Peanuts','Bronchitis'),
(nextval('seq_mh_id'),'00004','Hernia Repair','Peanuts','Migraine'),
(nextval('seq_mh_id'),'00005','Hernia Repair','Dust','Diabetes'),
(nextval('seq_mh_id'),'00006','Appendectomy','Dust','Arthritis'),
(nextval('seq_mh_id'),'00007','Gallbladder Removal','None','Bronchitis'),
(nextval('seq_mh_id'),'00008','Hernia Repair','Latex','Migraine'),
(nextval('seq_mh_id'),'00009','Hernia Repair','Dust','None'),
(nextval('seq_mh_id'),'00010','Knee Replacement','Latex','Depression'),
(nextval('seq_mh_id'),'00011','None','Dust','Bronchitis'),
(nextval('seq_mh_id'),'00012','Gallbladder Removal','Shellfish','Flu'),
(nextval('seq_mh_id'),'00013','Gallbladder Removal','Peanuts','Hypertension'),
(nextval('seq_mh_id'),'00014','Gallbladder Removal','Dust','Hypertension'),
(nextval('seq_mh_id'),'00015','Hernia Repair','Dust','Depression'),
(nextval('seq_mh_id'),'00016','Knee Replacement','Shellfish','Asthma'),
(nextval('seq_mh_id'),'00017','None','None','Diabetes'),
(nextval('seq_mh_id'),'00018','Hernia Repair','None','Pneumonia'),
(nextval('seq_mh_id'),'00019','None','Shellfish','Flu'),
(nextval('seq_mh_id'),'00020','Hernia Repair','Latex','Bronchitis'),
(nextval('seq_mh_id'),'00021','Gallbladder Removal','Dust','Pneumonia'),
(nextval('seq_mh_id'),'00022','Hernia Repair','Peanuts','Hypertension'),
(nextval('seq_mh_id'),'00023','Appendectomy','None','Flu'),
(nextval('seq_mh_id'),'00024','Hernia Repair','Dust','Asthma'),
(nextval('seq_mh_id'),'00025','Hernia Repair','Penicillin','None'),
(nextval('seq_mh_id'),'00026','Gallbladder Removal','Peanuts','Bronchitis'),
(nextval('seq_mh_id'),'00027','Hernia Repair','None','Depression'),
(nextval('seq_mh_id'),'00028','Appendectomy','Dust','Arthritis'),
(nextval('seq_mh_id'),'00029','Appendectomy','Dust','Migraine'),
(nextval('seq_mh_id'),'00030','Cataract Surgery','Latex','Asthma'),
(nextval('seq_mh_id'),'00031','Hernia Repair','Latex','Flu'),
(nextval('seq_mh_id'),'00032','Appendectomy','Shellfish','Flu'),
(nextval('seq_mh_id'),'00033','None','Penicillin','Migraine'),
(nextval('seq_mh_id'),'00034','None','Penicillin','Migraine'),
(nextval('seq_mh_id'),'00035','None','Penicillin','Arthritis'),
(nextval('seq_mh_id'),'00036','None','Latex','Hypertension'),
(nextval('seq_mh_id'),'00037','Knee Replacement','Peanuts','Bronchitis'),
(nextval('seq_mh_id'),'00038','Hernia Repair','None','Hypertension'),
(nextval('seq_mh_id'),'00039','Appendectomy','Peanuts','Pneumonia'),
(nextval('seq_mh_id'),'00040','None','Penicillin','Flu'),
(nextval('seq_mh_id'),'00041','None','Shellfish','Bronchitis'),
(nextval('seq_mh_id'),'00042','Knee Replacement','Latex','Diabetes'),
(nextval('seq_mh_id'),'00043','Cataract Surgery','Penicillin','Flu'),
(nextval('seq_mh_id'),'00044','Gallbladder Removal','Peanuts','None'),
(nextval('seq_mh_id'),'00045','Gallbladder Removal','None','Bronchitis'),
(nextval('seq_mh_id'),'00046','Gallbladder Removal','Peanuts','Arthritis'),
(nextval('seq_mh_id'),'00047','Hernia Repair','None','Hypertension'),
(nextval('seq_mh_id'),'00048','None','Penicillin','Arthritis'),
(nextval('seq_mh_id'),'00049','Cataract Surgery','Penicillin','Depression'),
(nextval('seq_mh_id'),'00050','Cataract Surgery','Latex','Depression'),
(nextval('seq_mh_id'),'00051','Gallbladder Removal','None','Arthritis'),
(nextval('seq_mh_id'),'00052','Appendectomy','Shellfish','Hypertension'),
(nextval('seq_mh_id'),'00053','Knee Replacement','Latex','Asthma'),
(nextval('seq_mh_id'),'00054','Gallbladder Removal','Penicillin','Migraine'),
(nextval('seq_mh_id'),'00055','Cataract Surgery','Latex','Pneumonia'),
(nextval('seq_mh_id'),'00056','Hernia Repair','Peanuts','Flu'),
(nextval('seq_mh_id'),'00057','Hernia Repair','Dust','Flu'),
(nextval('seq_mh_id'),'00058','Knee Replacement','Peanuts','Diabetes'),
(nextval('seq_mh_id'),'00059','Gallbladder Removal','None','Migraine'),
(nextval('seq_mh_id'),'00060','None','Latex','Asthma'),
(nextval('seq_mh_id'),'00061','Hernia Repair','Penicillin','Bronchitis'),
(nextval('seq_mh_id'),'00062','None','Peanuts','Arthritis'),
(nextval('seq_mh_id'),'00063','Knee Replacement','Peanuts','Arthritis'),
(nextval('seq_mh_id'),'00064','Cataract Surgery','Shellfish','Asthma'),
(nextval('seq_mh_id'),'00065','Knee Replacement','Shellfish','Depression'),
(nextval('seq_mh_id'),'00066','Knee Replacement','None','Pneumonia'),
(nextval('seq_mh_id'),'00067','Appendectomy','Latex','Diabetes'),
(nextval('seq_mh_id'),'00068','None','Peanuts','Depression'),
(nextval('seq_mh_id'),'00069','Appendectomy','Latex','Asthma'),
(nextval('seq_mh_id'),'00070','Hernia Repair','Dust','Diabetes'),
(nextval('seq_mh_id'),'00071','Appendectomy','Latex','Asthma'),
(nextval('seq_mh_id'),'00072','Gallbladder Removal','Penicillin','Asthma'),
(nextval('seq_mh_id'),'00073','Hernia Repair','None','Asthma'),
(nextval('seq_mh_id'),'00074','Gallbladder Removal','Penicillin','Pneumonia'),
(nextval('seq_mh_id'),'00075','Hernia Repair','Latex','Diabetes'),
(nextval('seq_mh_id'),'00076','Hernia Repair','None','Diabetes'),
(nextval('seq_mh_id'),'00077','Hernia Repair','Latex','Asthma'),
(nextval('seq_mh_id'),'00078','Appendectomy','Shellfish','Migraine'),
(nextval('seq_mh_id'),'00079','Gallbladder Removal','Dust','Depression'),
(nextval('seq_mh_id'),'00080','Appendectomy','Dust','None');