SELECT * FROM dim_patient_data
SELECT * FROM dim_doctors
SELECT * FROM dim_nurses
SELECT * FROM dim_diagnosis
SELECT * FROM dim_medical_history
SELECT * FROM dim_lab_results
SELECT * FROM fact_treatment
SELECT * FROM fact_insurance_claims
SELECT * FROM fact_vital_signs
SELECT * FROM fact_billing_info
